### ISSUE TITLE
npm ERR! Failed at the atom-languageclient@0.1.2 postinstall script 'postinstall-build --only-as-dependency build "npm run compile"'.

### ISSUE THREAD

**Issue by Johnathon332** [atom/atom-languageclient#166]
I am trying to install sonarlint for atom text editor but have come across this error.

```
Installing “sonarlint@1.0.2” failed.Hide output…

> atom-languageclient@0.1.2 postinstall C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient
> postinstall-build --only-as-dependency build "npm run compile"


> atom-languageclient@0.1.2 postinstall C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient
> postinstall-build --only-as-dependency build "npm run compile"


> atom-languageclient@0.1.2 prepublish C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient
> npm run clean && npm run compile


> atom-languageclient@0.1.2 clean C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient
> rm -rf build

C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr
`-- (empty)


npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! atom-languageclient@0.1.2 clean: `rm -rf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.2 clean script 'rm -rf build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\babel-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--only=dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! atom-languageclient@0.1.2 prepublish: `npm run clean && npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.2 prepublish script 'npm run clean && npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\atom-languageclient\npm-debug.log
{ Error: Command failed: C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\Users\Johnathon332\AppData\Local\atom\app-1.23.2\resources\app\apm\bin\node.exe" "C:\Users\Johnathon332\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" install --only=dev"

    at ChildProcess.<anonymous> (C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\node_modules\sonarlint\node_modules\postinstall-build\index.js:53:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /d /s /c ""C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" install --only=dev"' }
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JOHNAT~1\AppData\Local\Temp\apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr\package.json'
npm WARN apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr No description
npm WARN apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr No repository field.
npm WARN apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr No README data
npm WARN apm-install-dir-11806-10740-1p6l9uz.gd9xczyqfr No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Johnathon332\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Johnathon332\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Johnathon332\\.atom\\.apmrc" "install" "C:\\Users\\JOHNAT~1\\AppData\\Local\\Temp\\d-11806-10740-afxcyf.n2splm1jor\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style" "--msvs_version=2013"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! atom-languageclient@0.1.2 postinstall: `postinstall-build --only-as-dependency build "npm run compile"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-languageclient@0.1.2 postinstall script 'postinstall-build --only-as-dependency build "npm run compile"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-languageclient package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     postinstall-build --only-as-dependency build "npm run compile"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-languageclient
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-languageclient
npm ERR! There is likely additional logging output above.
```

**Comment by damieng** [comment]
The build scripts for atom-languageclient only really work on mac or bash but this should not be a problem as the published version is all preprocessed and ready to go. 

It would seem the author is directly linking to the git source code instead of using the published version of atom-languageclient https://github.com/SonarSource/sonarlint-atom/blob/master/package.json#L40  

You can file an issue about there there. (or manually just change the package.json for now)

**Comment by Johnathon332** [comment]
Where can I find the published version

**Comment by Arcanemagus** [comment]
https://www.npmjs.com/package/atom-languageclient or simply putting a version number instead of the git address of a fork.
