### ISSUE TITLE
`Uncaught Error: Connection is closed.` on invalid enum field in config

### ISSUE THREAD

**Issue by alexfedoseev** [atom/atom-languageclient#194]
I noticed this error when I was implementing config UI for https://github.com/reasonml-editor/atom-ide-reason

Sometimes when I type not fast enough in enum field in package's settings I get hard error `Uncaught Error: Connection is closed`. Prolly debouncing config updates might solve this issue?

Stack:

```
At /Users/Alex/.atom/packages/ide-reason/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-reason/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-reason/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-reason/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/languageclient.js:341:19)
    at LanguageClientConnection.didChangeConfiguration (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/languageclient.js:120:14)
    at _disposable.add.atom.config.observe (/packages/ide-flowtype/node_modules/atom-languageclient/build/lib/auto-languageclient.js:262:36)
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:676:22
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:248:20)
    at SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:315:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1724:26)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

**Comment by damieng** [comment]
Hey @daviwil can you think how the config observable work might cause this?

**Comment by UziTech** [comment]
Development of [atom-languageclient](https://www.npmjs.com/package/atom-languageclient) has officially moved to https://github.com/atom-ide-community/atom-languageclient 🎉 

If this is still an issue please consider opening an issue on that repo.
